stack: fold flash programming into main stack, use prebuilt fw images

diff --git a/sn-stack/docker-compose.yml b/sn-stack/docker-compose.yml
--- a/sn-stack/docker-compose.yml
+++ b/sn-stack/docker-compose.yml
@@ -60,6 +60,48 @@ services:
         touch /bitfiles/ok
         sleep infinity
 
+  smartnic-flash:
+    <<: *labtools-service
+    hostname: smartnic-flash
+    init: true
+    user: root
+    privileged: true
+    depends_on:
+      smartnic-unpack:
+        condition: service_started
+    volumes:
+      - bitfiles:/bitfiles:ro
+      - ${SN_STACK_ROOT-.}/smartnic-hw/scripts:/scripts:ro
+    network_mode: none
+    entrypoint:
+      - /bin/bash
+      - -c
+      - -e
+      - -o
+      - pipefail
+      - -x
+      - |
+        while [ ! -e /bitfiles/ok ] ; do
+          echo "Waiting for bitfiles to be unpacked..."
+          sleep 1
+        done
+        /scripts/program_flash.sh \
+          localhost:3121 \
+          "${HW_TARGET_SERIAL:-*}" \
+          /bitfiles/esnet-smartnic.mcs \
+          $FPGA_PCIE_DEV
+        file /bitfiles/esnet-smartnic.bit
+        if [ $$? ] ; then
+          # Flash update has succeeded, all OK
+          echo "Flash Update Successful"
+          exit 0
+        else
+          echo "Flash Update Attempted and Failed, Not Healthy!"
+          exit 1
+        fi
+    profiles:
+      - smartnic-flash
+
   smartnic-hw:
     <<: *labtools-service
     hostname: smartnic-hw
