stack: add an actual flash write capability to smartnic-flash service

diff --git a/sn-stack/docker-compose.yml b/sn-stack/docker-compose.yml
--- a/sn-stack/docker-compose.yml
+++ b/sn-stack/docker-compose.yml
@@ -42,6 +42,8 @@ services:
     restart: unless-stopped
     env_file:
       - ${SN_STACK_ROOT-.}/buildinfo.env
+    environment:
+      - SMARTNIC_UPDATE_FLASH=${SMARTNIC_UPDATE_FLASH-}
     tmpfs:
       - /status
     volumes:
@@ -50,8 +52,8 @@ services:
     healthcheck:
       test: ["CMD-SHELL", "/usr/bin/test -e /status/ok"]
       interval: 10s
-      timeout: 10s
-      retries: 6
+      timeout: 25m
+      retries: 150
       start_period: 10s
     entrypoint:
       - /bin/bash
@@ -63,17 +65,22 @@ services:
       - |
         dpkg -i \
           /debs/esnet-smartnic1_1.0.0-$${SN_FW_VER}_amd64.deb
-        touch /status/ok
+        if [ ! -z "$${SMARTNIC_UPDATE_FLASH}" ] ; then
+          /scripts/program_flash.sh \
+            xilinx-hwserver:3121 \
+            "${HW_TARGET_SERIAL:-*}" \
+            /usr/lib/firmware/esnet-smartnic/esnet-smartnic.mcs
+          if [ $$? ] ; then
+            # Flash update has succeeded, all OK
+            touch /status/ok
+          else
+            echo "Flash Update Attempted and Failed, Not Healthy!"
+          fi
+        else
+          # No request to update flash, assume everything is ok
+          touch /status/ok
+        fi
         sleep infinity
-        # /scripts/program_card.sh \
-        #   xilinx-hwserver:3121 \
-        #   "${HW_TARGET_SERIAL:-*}" \
-        #   /usr/lib/firmware/esnet-smartnic/esnet-smartnic.bit \
-        #   # FORCE
-        # if [ $$? ] ; then
-        #   touch /status/ok
-        #   sleep infinity
-        # fi
 
   smartnic-bitfile:
     hostname: smartnic-bitfile
